In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.DataFrame()
index = [ ('Archaea',''),
         ('Bacteria',''),
          ('Viruses',''),
          ('Other',''),
          ('Eukaryota', 'Human'), 
         ('Eukaryota','Other Mammalia'), 
         ('Eukaryota','Other Vertebrata'),
         ('Eukaryota','Viridiplantae'),
          ('Eukaryota','Fungi'),
           ('Eukaryota','Insecta'),
         ('Eukaryota','Nematoda'),
         ('Eukaryota','Other') ,
         ('Total','') ]
df = df.reindex(index)
df

Empty DataFrame
Columns: []
Index: [(Archaea, ), (Bacteria, ), (Viruses, ), (Other, ), (Eukaryota, Human), (Eukaryota, Other Mammalia), (Eukaryota, Other Vertebrata), (Eukaryota, Viridiplantae), (Eukaryota, Fungi), (Eukaryota, Insecta), (Eukaryota, Nematoda), (Eukaryota, Other), (Total, )]

Release 2019_11 of 11-Dec-19 of UniProtKB/Swiss-Prot contains 561568 sequence entries,

comprising 201997950 amino acids abstracted from 269719 references. 



224 sequences have been added since release 2019_10, the sequence data of

22 existing entries has been updated and the annotations of

561344 entries have been revised.


  
   
   Kingdom        sequences (% of the database)

    Archaea           19581 (  3%)

    Bacteria         334357 ( 60%)

    Eukaryota        190642 ( 34%)

    Viruses           16988 (  3%)





   Within Eukaryota:



   



    Category            sequences (% of Eukaryota) (% of the complete database)

     Human                  20368 ( 11%)           (  4%)

     Other Mammalia         46839 ( 25%)           (  8%)

     Other Vertebrata       18434 ( 10%)           (  3%)

     Viridiplantae          40216 ( 21%)           (  7%)

     Fungi                  34262 ( 18%)           (  6%)

     Insecta                 9354 (  5%)           (  2%)

     Nematoda                5015 (  3%)           (  1%)

     Other                  16154 (  8%)           (  3%)

In [11]:
sp_Archaea=19581  
sp_Bacteria=334357 
sp_Eukaryota=190642 
sp_Viruses=16988

sp = [sp_Archaea, sp_Bacteria, sp_Viruses]
index = [('Archaea',''), ( 'Bacteria', ''), ('Viruses','')]
df.loc[index,'SwissProt']  = sp

sp_e_Human=20368 
sp_e_Other_Mammalia=46839 
sp_e_Other_Vertebrata=18434 
sp_e_Viridiplantae=40216 
sp_e_Fungi=34262 
sp_e_Insecta=9354 
sp_e_Nematoda=5015
sp_e_Other=16154 

sp_euks = [sp_e_Human, 
           sp_e_Other_Mammalia, 
           sp_e_Other_Vertebrata, 
           sp_e_Viridiplantae, 
           sp_e_Fungi,
           sp_e_Insecta,  
           sp_e_Nematoda, 
           sp_e_Other  ]

index = [ ('Eukaryota','Human'),
          ('Eukaryota','Other Mammalia'),
          ('Eukaryota','Other Vertebrata'),
          ('Eukaryota','Viridiplantae'),
          ('Eukaryota','Fungi'),
          ('Eukaryota','Insecta'),
          ('Eukaryota','Nematoda'),
          ('Eukaryota','Other') ]

df.loc[index, 'SwissProt'] = sp_euks         
         
    
assert df['SwissProt'].sum() == 561568

Release 2019_11 of 11-Dec-2019 of UniProtKB/TrEMBL contains 179250561 sequence entries,
comprising 60319985647 amino acids.

2336012 sequences have been added since release 2019_10, the sequence data of
110192 existing entries has been updated and the annotations of
176406530 entries have been revised. This represents an increase of 1%.

Number of fragments: 17484051

Protein existence (PE):              entries      %
1: Evidence at protein level          148886     0.08%
2: Evidence at transcript level      1302187     0.73%
3: Inferred from homology           46284707    25.82%
4: Predicted                       131514781    73.37%
5: Uncertain                               0     0.00%



   Kingdom        sequences (% of the database)
    Archaea         3933054 (  2%)
    Bacteria      128577841 ( 72%)
    Eukaryota      40749091 ( 23%)
    Viruses         4303549 (  2%)
    Other           1687026 ( <1%)



   Within Eukaryota:



    Category            sequences (% of Eukaryota) (% of the complete database)
     Human                 168078 (  0%)           (  0%)
     Other Mammalia       3179841 (  8%)           (  2%)
     Other Vertebrata     4807649 ( 12%)           (  3%)
     Viridiplantae        9314135 ( 23%)           (  5%)
     Fungi               11564971 ( 28%)           (  6%)
     Insecta              3811058 (  9%)           (  2%)
     Nematoda             1847926 (  5%)           (  1%)
     Other                6055433 ( 15%)           (  3%)

In [12]:
tr_Archaea=3933054 
tr_Bacteria=128577841 
tr_Eukaryota=40749091
tr_Viruses=4303549 
tr_Other= 1687026 

tr = [tr_Archaea,tr_Bacteria, tr_Viruses, tr_Other  ]
index = [('Archaea',''), ( 'Bacteria', ''), ('Viruses',''), ('Other','')]
df.loc[index,'TREMBL']  = tr

print(np.sum(tr))
    
tr_e_Human= 168078 
tr_e_Other_Mammalia=3179841 
tr_e_Other_Vertebrata=4807649 
tr_e_Viridiplantae=9314135
tr_e_Fungi= 11564971
tr_e_Insecta=3811058
tr_e_Nematoda=1847926 
tr_e_Other=6055433 

tr_euks = [ tr_e_Human, 
           tr_e_Other_Mammalia,
           tr_e_Other_Vertebrata,
           tr_e_Viridiplantae , 
           tr_e_Fungi,
           tr_e_Insecta,
          tr_e_Nematoda, 
           tr_e_Other  ]

index = [ ('Eukaryota','Human'),
          ('Eukaryota','Other Mammalia'),
          ('Eukaryota','Other Vertebrata'),
          ('Eukaryota','Viridiplantae'),
          ('Eukaryota','Fungi'),
          ('Eukaryota','Insecta'),
          ('Eukaryota','Nematoda'),
          ('Eukaryota','Other') ]

df.loc[index, 'TREMBL'] = tr_euks         


assert df['TREMBL'].sum() == 179250561
index = [ ('Total','') ]
df['Total'] = df.sum(axis=1)
df.loc[ index, :] = df.sum().values
df

138501470

                               SwissProt       TREMBL        Total
(Archaea, )                      19581.0    3933054.0    3952635.0
(Bacteria, )                    334357.0  128577841.0  128912198.0
(Viruses, )                      16988.0    4303549.0    4320537.0
(Other, )                            NaN    1687026.0    1687026.0
(Eukaryota, Human)               20368.0     168078.0     188446.0
(Eukaryota, Other Mammalia)      46839.0    3179841.0    3226680.0
(Eukaryota, Other Vertebrata)    18434.0    4807649.0    4826083.0
(Eukaryota, Viridiplantae)       40216.0    9314135.0    9354351.0
(Eukaryota, Fungi)               34262.0   11564971.0   11599233.0
(Eukaryota, Insecta)              9354.0    3811058.0    3820412.0
(Eukaryota, Nematoda)             5015.0    1847926.0    1852941.0
(Eukaryota, Other)               16154.0    6055433.0    6071587.0
(Total, )                       561568.0  179250561.0  179812129.0

In [13]:
df['%'] =  ( df['Total'].astype(float) / float(df['Total'][:-1].sum() ) ) * 100
df['%'] = df['%'].apply(lambda x : np.round(x, 2))

In [14]:
index = pd.MultiIndex.from_tuples(df.index)
df = df.replace(np.nan, 0)
df['SwissProt'] = df['SwissProt'].astype(int)
df['TREMBL'] = df['TREMBL'].astype(int)
df['Total'] = df['Total'].astype(int)

df = df.reindex(index)

In [15]:
df.reset_index().to_excel('analysis/supplementary/S1_table.xlsx')

In [16]:
df

                            SwissProt     TREMBL      Total       %
Archaea                         19581    3933054    3952635    2.20
Bacteria                       334357  128577841  128912198   71.69
Viruses                         16988    4303549    4320537    2.40
Other                               0    1687026    1687026    0.94
Eukaryota Human                 20368     168078     188446    0.10
          Other Mammalia        46839    3179841    3226680    1.79
          Other Vertebrata      18434    4807649    4826083    2.68
          Viridiplantae         40216    9314135    9354351    5.20
          Fungi                 34262   11564971   11599233    6.45
          Insecta                9354    3811058    3820412    2.12
          Nematoda               5015    1847926    1852941    1.03
          Other                 16154    6055433    6071587    3.38
Total                          561568  179250561  179812129  100.00